services:
  - type: web
    name: linkedin-clone-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: MAILTRAP_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        sync: false
      - key: CLIENT_URL
        value: https://kajalraj11.github.io/linkedin-clone
