services:
  - type: web
    name: linkedin-clone-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MAILTRAP_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLIENT_URL
        value: https://kajalraj11.github.io/linkedin-clone

  - type: web
    name: linkedin-clone-frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npx serve -s frontend/dist -l 3000
    envVars:
      - key: VITE_API_URL
        value: https://linkedin-clone-backend.onrender.com
